version: '1.0'
services:
  web-server:
    build: 
      dockerfile: dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql-server
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: estudantes

  mysql-server:
    image: mysql:8.0.19
    volumes:
      - estudantes-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: estudantes

volumes:
  estudantes-mysql-data:
