version: '1.0'
services:
  web-server:
    build: 
      dockerfile: dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql-server
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: estudantes

  mysql-server:
    image: mysql:8.0.19
    ports:
      - "3306:3306"
    volumes:
      - estudantes-mysql-data:/var/lib/mysql
      - "./database scripts/criarBancoDeDados.sql:/docker-entrypoint-initdb.d/init0.sql"
      - "./database scripts/criarTabelas.sql:/docker-entrypoint-initdb.d/init1.sql"
      - "./database scripts/criarUsuario.sql:/docker-entrypoint-initdb.d/init2.sql"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: estudantes

volumes:
  estudantes-mysql-data:
